class_smells:
  god_class_wmc: 10
  god_class_tcc: 0.5
  god_class_atfd: 2
  god_class_loc: 200
  mfa_lcom: 0.5
  mfa_wmc: 10
  mfa_nof: 3
  mfa_nom: 8
  deficient_encapsulation_woa: 0.1
  lazy_class_nom: 10
  lazy_class_nof: 10
  lazy_class_dit: 5
  massive_vc_nom: 15
  massive_vc_noa: 12

method_smells:
  long_method_loc: 20
  long_method_cc: 5
  long_method_noi: 15

structural_smells:
  message_chain_length: 2
  broken_hierarchy_dit: 2
  cyclic_dependency_length: 1
  feature_envy_threshold: 2
  dense_structure_degree: 0.3
  weakened_modularity_ratio: 0.8

module_smells:
  duplicate_block_tokens: 100
  imperative_abstraction_max_exec_count: 1
  imperative_abstraction_exec_ratio: 0.15
  insufficient_modularization_max_line_count: 30
  insufficient_modularization_max_nesting_depth: 2
  insufficient_modularization_max_type_declarations: 1
  missing_abstraction_max_elements: 1
  unstructured_module_max_elements: 2