class_smells:
  god_class_wmc: 10
  god_class_tcc: 0.5
  god_class_atfd: 2
  god_class_loc: 200
  mfa_lcom: 0.5
  mfa_wmc: 10
  mfa_nof: 3
  mfa_nom: 8
  deficient_encapsulation_woa: 0.1
  lazy_class_nom: 10
  lazy_class_nof: 10
  lazy_class_dit: 5

method_smells:
  long_method_loc: 20
  long_method_cc: 5
  long_method_noi: 15

structural_smells:
  message_chain_length: 2
  broken_hierarchy_dit: 2
  cyclic_dependency_length: 1
  feature_envy_threshold: 2